dataset:
  augmentation:
    homographic:
      border_reflect: true
      enable: true
      params:
        allow_artifacts: true
        max_angle: 1.57
        patch_ratio: 0.85
        perspective: true
        perspective_amplitude_x: 0.2
        perspective_amplitude_y: 0.2
        rotation: true
        scaling: true
        scaling_amplitude: 0.2
        translation: true
        translation_overflow: 0.05
      valid_border_margin: 0
    photometric:
      enable: true
      params:
        additive_gaussian_noise:
          stddev_range:
          - 0
          - 0.06
        additive_shade:
          kernel_size_range:
          - 50
          - 100
          transparency_range:
          - -0.5
          - 0.8
        additive_speckle_noise:
          prob_range:
          - 0
          - 0.0035
        motion_blur:
          max_kernel_size: 3
        random_brightness:
          max_abs_change: 0.15
        random_contrast:
          strength_range:
          - 0.3
          - 1.8
      primitives:
      - random_brightness
      - random_contrast
      - additive_speckle_noise
      - additive_gaussian_noise
      - additive_shade
      - motion_blur
  filename: /Users/antonia/dev/UNITN/remote_sensing_systems/multipoint/data/data_arss/training.hdf5
  height: 232
  keypoints_filename: /Users/antonia/dev/UNITN/remote_sensing_systems/multipoint/data/data_arss/labels.hdf5
  random_pairs: true
  single_image: false
  type: ImagePairDataset
  width: 312
loss:
  descriptor_loss: true
  descriptor_loss_threshold: 4.0
  descriptor_loss_use_mask: true
  detector_loss: true
  detector_use_cross_entropy: true
  lambda: 1.0
  lambda_d: 250
  negative_margin: 0.2
  positive_margin: 1.0
  sparse_descriptor_loss: false
  sparse_descriptor_loss_num_cell_divisor: 64
  type: SuperPointLoss
model:
  bn_first: false
  descriptor_head: true
  descriptor_size: 64
  final_batchnorm: true
  intepolation_mode: bilinear
  multispectral: false
  normalize_descriptors: true
  reflection_pad: true
  type: MultiPoint
training:
  allow_gpu: true
  batchsize: 1
  learningrate: 1e-4
  n_epochs: 3
  num_worker: 4
  output_directory: model_weights/multipoint-retrained
  save_every_n_epoch: 5
  use_writer: true
  validation:
    compute_validation_loss: false
